name: Pull Test Images
description: |
  Pre-pull all container images required for tests to avoid rate limits.
  Images are cached on the runner for subsequent test steps.

runs:
  using: composite
  steps:
    # - name: Login to Container Registry
    #   uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ github.token }}

    - name: Pull required test images
      run: ./scripts/installation/pull-test-images.sh
      shell: bash

    # - name: Logout from Container Registry
    #   if: always()
    #   run: |
    #     set -eu

    #     __LIB_DIR="./scripts"
    #     # shellcheck disable=SC1091
    #     . "${__LIB_DIR}/lib.sh"

    #     # Logout may fail if not logged in, ignore errors
    #     docker logout ghcr.io || warn "Failed to logout from ghcr.io (may not be logged in)"
    #   shell: sh
