#
# area
#
# area/grpc
area/grpc:
  - pkg/server/grpc/**
  - pkg/server/grpc/**/*
# area/api
area/api:
  - api/**
  - api/**/*
# area/arm64:
area/build:
  - builder/**
  - "**/Makefile"
  - "**/Dockerfile"
  - go.sum
  - go.mod
  - staticcheck.conf
  - .github/**
  - .clang-format
  - .dockerignore
area/capture:
  - "*capture*"
# area/co-re:
area/ebpf:
  - pkg/ebpf/*
  - pkg/ebpf/**/*
area/events:
  - pkg/events/*
  - pkg/events/**/*
area/filtering:
  - pkg/filters/*
  - pkg/filters/**/*
area/flags:
  - pkg/cmd/flags/*
  - pkg/cmd/flags/**/*
area/kubernetes:
  - deploy/*
  - deploy/**/*
area/logging:
  - pkg/logger/*
  - pkg/logger/**/*
  - pkg/errfmt/*
  - pkg/errfmt/**/*
# area/network:
area/performance:
  - pkg/metrics/*
  - pkg/metrics/**/*
area/release:
  - packaging/*
  - packaging/**/*
# area/rules:
area/signatures:
  - pkg/signatures/*
  - pkg/signatures/**/*
  - signatures/*
  - signatures/**/*
  - "**/*.rego"
area/testing:
  - tests/*
  - tests/**/*
  - "**/*_test.go"
  - "**/*_test.rego"
# area/uprobe:
area/UX:
  - pkg/cmd/*
  - pkg/cmd/**/*
  - cmd/*
  - cmd/**/*
#
# kind
#
kind/documentation:
  - docs/*
  - docs/**/*
  - "**/*.md"
  - mkdocs.yml
  - NOTICE
  - LICENSE
  - cmd/tracee-gptdocs/*
# kind/bug:
# kind/chore:
# kind/feature:
