
builds:
- main: ./main.go
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - "-s -w -X github.com/aquasecurity/tracee/tracee.ebpfProgramBase64Injected={{.Env.EBPFPROGRAM_BASE64}}"
archives:
- name_template: "{{ .ProjectName }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "docker.io/aquasec/tracee:{{ .Version }}"
      - "docker.io/aquasec/tracee:latest"
    binaries:
      - tracee
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.vendor=Aqua Security"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/aquasecurity/tracee"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"