apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesJson6902:
- target:
    version: v1
    kind: DaemonSet
    name: tracee
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args
      value: 
        - --webhook http://tracee-webhook:2801 
        - --webhook-template ./templates/falcosidekick.tmpl 
        - --webhook-content-type application/json

