blob-perf-buffer-size: 1024
cache:
    type: none
    # size: 1024

capture:
  #- write
  #- exec
  #- network

policy:
  - /path/to/policy.yaml
  #- /path/to/policy-directory

proctree:
    source: none
    # cache:
    #     process: 8192
    #     thread: 4096

capabilities:
    bypass: false
    # add:
    #     - cap_sys_admin
    #     - cap_syslog
    # drop:
    #     - cap_chown

metrics-endpoint: true

server:
    http-address: "127.0.0.1:8080"
    grpc-address: "unix:/var/run/tracee.sock"
    metrics: true
    healthz: true
    pprof: true
    pyroscope: true
dnscache: enable

containers:
    enrich: false
    # enrich: true
    # cgroupfs:
    #     path: /host/sys/fs/cgroup
    #     force: true
    # sockets:
    #     - runtime: containerd
    #       socket: /var/run/containerd/containerd.sock
    #     - runtime: docker
    #       socket: /var/run/docker.sock

events:
  #- open
  #- execve

healthz: false

install-path: /tmp/tracee

listen-addr: :3366

log:
    level: info
    # file: "/path/to/log/file.log"
    # aggregate:
    #     enabled: true
    #     flush-interval: "5s"
    # filters:
    #     libbpf: false
    #     in:
    #     msg:
    #         - SampleMessage1
    #         - SampleMessage2
    #     pkg:
    #         - package1
    #         - package2
    #     file:
    #         - file1.go
    #         - file2.go
    #     level:
    #         - warn
    #         - error
    #     regex:
    #         - ^pattern1
    #         - ^pattern2
    #     out:
    #     msg:
    #         - ExcludedMessage1
    #     pkg:
    #         - excludedPackage
    #     file:
    #         - excludedFile.go
    #     level:
    #         - debug
    #     regex:
    #         - ^excludedPattern

scope:  
  #- uid=1000
  #- global
  #- pid=1000
  #- mntns=4026531840
  #- pidns=4026531836    
  #- uts=ab356bc4dd554
  #- comm=uname
  #- container
  #- not-container
  #- tree=1000
  #- executable=/usr/bin/dig
  #- follow

metrics: false

output:
    # destinations:
    #   - name: destination_name
    #     type: file | webhook | forward
    #     path: path in case of type == file
    #     url: url in case of type == webhook or type == forward
    #     format: json | gotemplate=/path/to/template.tpl | table | table-verbose
    
    # streams:
    #   - name: stream_name
    #     destinations: 
    #       - destination_name
    #     filters:
    #       events:
    #         - event_to_filter
    #       policies:
    #         - policy_to_filter
    #     buffer:
    #       mode: drop
    #       size: 1024

    # options:
    #     none: false
    #     stack-addresses: true
    #     exec-env: false
    #     exec-hash: dev-inode
    #     parse-arguments: true
    #     sort-events: false

perf-buffer-size: 1024

pprof: false

pyroscope: false

signatures-dir: ""
