// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/datastores/ipreputation.proto

package datastores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReputationStatus indicates the reputation classification
type ReputationStatus int32

const (
	ReputationStatus_REPUTATION_UNKNOWN    ReputationStatus = 0
	ReputationStatus_REPUTATION_ALLOW      ReputationStatus = 1
	ReputationStatus_REPUTATION_DENY       ReputationStatus = 2
	ReputationStatus_REPUTATION_SUSPICIOUS ReputationStatus = 3
)

// Enum value maps for ReputationStatus.
var (
	ReputationStatus_name = map[int32]string{
		0: "REPUTATION_UNKNOWN",
		1: "REPUTATION_ALLOW",
		2: "REPUTATION_DENY",
		3: "REPUTATION_SUSPICIOUS",
	}
	ReputationStatus_value = map[string]int32{
		"REPUTATION_UNKNOWN":    0,
		"REPUTATION_ALLOW":      1,
		"REPUTATION_DENY":       2,
		"REPUTATION_SUSPICIOUS": 3,
	}
)

func (x ReputationStatus) Enum() *ReputationStatus {
	p := new(ReputationStatus)
	*p = x
	return p
}

func (x ReputationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReputationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1beta1_datastores_ipreputation_proto_enumTypes[0].Descriptor()
}

func (ReputationStatus) Type() protoreflect.EnumType {
	return &file_api_v1beta1_datastores_ipreputation_proto_enumTypes[0]
}

func (x ReputationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReputationStatus.Descriptor instead.
func (ReputationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_ipreputation_proto_rawDescGZIP(), []int{0}
}

// IPAddressKey is used for IP-based lookups
type IPAddressKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // IP address (IPv4 or IPv6)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddressKey) Reset() {
	*x = IPAddressKey{}
	mi := &file_api_v1beta1_datastores_ipreputation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddressKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressKey) ProtoMessage() {}

func (x *IPAddressKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_ipreputation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressKey.ProtoReflect.Descriptor instead.
func (*IPAddressKey) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_ipreputation_proto_rawDescGZIP(), []int{0}
}

func (x *IPAddressKey) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IPReputation represents threat intelligence data for an IP address
type IPReputation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReputationStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=tracee.v1beta1.datastores.ReputationStatus" json:"status,omitempty"`
	Severity      int32                  `protobuf:"varint,2,opt,name=severity,proto3" json:"severity,omitempty"` // 1-10 severity score
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`          // e.g., ["botnet", "malware", "c2"]
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional key-value metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPReputation) Reset() {
	*x = IPReputation{}
	mi := &file_api_v1beta1_datastores_ipreputation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPReputation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReputation) ProtoMessage() {}

func (x *IPReputation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_ipreputation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReputation.ProtoReflect.Descriptor instead.
func (*IPReputation) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_ipreputation_proto_rawDescGZIP(), []int{1}
}

func (x *IPReputation) GetStatus() ReputationStatus {
	if x != nil {
		return x.Status
	}
	return ReputationStatus_REPUTATION_UNKNOWN
}

func (x *IPReputation) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *IPReputation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IPReputation) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *IPReputation) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_v1beta1_datastores_ipreputation_proto protoreflect.FileDescriptor

const file_api_v1beta1_datastores_ipreputation_proto_rawDesc = "" +
	"\n" +
	")api/v1beta1/datastores/ipreputation.proto\x12\x19tracee.v1beta1.datastores\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\fIPAddressKey\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xd2\x02\n" +
	"\fIPReputation\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.tracee.v1beta1.datastores.ReputationStatusR\x06status\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\x05R\bseverity\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12=\n" +
	"\flast_updated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12Q\n" +
	"\bmetadata\x18\x05 \x03(\v25.tracee.v1beta1.datastores.IPReputation.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*p\n" +
	"\x10ReputationStatus\x12\x16\n" +
	"\x12REPUTATION_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10REPUTATION_ALLOW\x10\x01\x12\x13\n" +
	"\x0fREPUTATION_DENY\x10\x02\x12\x19\n" +
	"\x15REPUTATION_SUSPICIOUS\x10\x03BBZ@github.com/aquasecurity/tracee/api/v1beta1/datastores;datastoresb\x06proto3"

var (
	file_api_v1beta1_datastores_ipreputation_proto_rawDescOnce sync.Once
	file_api_v1beta1_datastores_ipreputation_proto_rawDescData []byte
)

func file_api_v1beta1_datastores_ipreputation_proto_rawDescGZIP() []byte {
	file_api_v1beta1_datastores_ipreputation_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_datastores_ipreputation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_datastores_ipreputation_proto_rawDesc), len(file_api_v1beta1_datastores_ipreputation_proto_rawDesc)))
	})
	return file_api_v1beta1_datastores_ipreputation_proto_rawDescData
}

var file_api_v1beta1_datastores_ipreputation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1beta1_datastores_ipreputation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1beta1_datastores_ipreputation_proto_goTypes = []any{
	(ReputationStatus)(0),         // 0: tracee.v1beta1.datastores.ReputationStatus
	(*IPAddressKey)(nil),          // 1: tracee.v1beta1.datastores.IPAddressKey
	(*IPReputation)(nil),          // 2: tracee.v1beta1.datastores.IPReputation
	nil,                           // 3: tracee.v1beta1.datastores.IPReputation.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_v1beta1_datastores_ipreputation_proto_depIdxs = []int32{
	0, // 0: tracee.v1beta1.datastores.IPReputation.status:type_name -> tracee.v1beta1.datastores.ReputationStatus
	4, // 1: tracee.v1beta1.datastores.IPReputation.last_updated:type_name -> google.protobuf.Timestamp
	3, // 2: tracee.v1beta1.datastores.IPReputation.metadata:type_name -> tracee.v1beta1.datastores.IPReputation.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1beta1_datastores_ipreputation_proto_init() }
func file_api_v1beta1_datastores_ipreputation_proto_init() {
	if File_api_v1beta1_datastores_ipreputation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_datastores_ipreputation_proto_rawDesc), len(file_api_v1beta1_datastores_ipreputation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1beta1_datastores_ipreputation_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_datastores_ipreputation_proto_depIdxs,
		EnumInfos:         file_api_v1beta1_datastores_ipreputation_proto_enumTypes,
		MessageInfos:      file_api_v1beta1_datastores_ipreputation_proto_msgTypes,
	}.Build()
	File_api_v1beta1_datastores_ipreputation_proto = out.File
	file_api_v1beta1_datastores_ipreputation_proto_goTypes = nil
	file_api_v1beta1_datastores_ipreputation_proto_depIdxs = nil
}
