// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/datastores/writable.proto

package datastores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataEntry represents a single key-value pair for writable datastores
// Keys and data are packed as google.protobuf.Any for type safety and extensibility
type DataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *anypb.Any             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`   // Key as protobuf Any (e.g., IPAddressKey from ipreputation.proto)
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Data as protobuf Any (e.g., IPReputation from ipreputation.proto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{0}
}

func (x *DataEntry) GetKey() *anypb.Any {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DataEntry) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"` // Name of the target datastore
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                        // Source identifier for this data
	Entry         *DataEntry             `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`                          // The data entry to write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataRequest) Reset() {
	*x = WriteDataRequest{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataRequest) ProtoMessage() {}

func (x *WriteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataRequest.ProtoReflect.Descriptor instead.
func (*WriteDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{1}
}

func (x *WriteDataRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *WriteDataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WriteDataRequest) GetEntry() *DataEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type WriteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataResponse) Reset() {
	*x = WriteDataResponse{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataResponse) ProtoMessage() {}

func (x *WriteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataResponse.ProtoReflect.Descriptor instead.
func (*WriteDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{2}
}

type WriteBatchDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Entries       []*DataEntry           `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchDataRequest) Reset() {
	*x = WriteBatchDataRequest{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchDataRequest) ProtoMessage() {}

func (x *WriteBatchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchDataRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{3}
}

func (x *WriteBatchDataRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *WriteBatchDataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WriteBatchDataRequest) GetEntries() []*DataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WriteBatchDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrittenCount  int32                  `protobuf:"varint,1,opt,name=written_count,json=writtenCount,proto3" json:"written_count,omitempty"` // Number of entries successfully written
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchDataResponse) Reset() {
	*x = WriteBatchDataResponse{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchDataResponse) ProtoMessage() {}

func (x *WriteBatchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchDataResponse.ProtoReflect.Descriptor instead.
func (*WriteBatchDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{4}
}

func (x *WriteBatchDataResponse) GetWrittenCount() int32 {
	if x != nil {
		return x.WrittenCount
	}
	return 0
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Key           *anypb.Any             `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // Key remains separate for delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDataRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *DeleteDataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeleteDataRequest) GetKey() *anypb.Any {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{6}
}

type ClearSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // Clear all data from this source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSourceRequest) Reset() {
	*x = ClearSourceRequest{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSourceRequest) ProtoMessage() {}

func (x *ClearSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSourceRequest.ProtoReflect.Descriptor instead.
func (*ClearSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{7}
}

func (x *ClearSourceRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *ClearSourceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ClearSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // Number of entries deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSourceResponse) Reset() {
	*x = ClearSourceResponse{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSourceResponse) ProtoMessage() {}

func (x *ClearSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSourceResponse.ProtoReflect.Descriptor instead.
func (*ClearSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{8}
}

func (x *ClearSourceResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{9}
}

func (x *ListSourcesRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []string               `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datastores_writable_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datastores_writable_proto_rawDescGZIP(), []int{10}
}

func (x *ListSourcesResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_api_v1beta1_datastores_writable_proto protoreflect.FileDescriptor

const file_api_v1beta1_datastores_writable_proto_rawDesc = "" +
	"\n" +
	"%api/v1beta1/datastores/writable.proto\x12\x19tracee.v1beta1.datastores\x1a\x19google/protobuf/any.proto\"]\n" +
	"\tDataEntry\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03key\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\x85\x01\n" +
	"\x10WriteDataRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12:\n" +
	"\x05entry\x18\x03 \x01(\v2$.tracee.v1beta1.datastores.DataEntryR\x05entry\"\x13\n" +
	"\x11WriteDataResponse\"\x8e\x01\n" +
	"\x15WriteBatchDataRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12>\n" +
	"\aentries\x18\x03 \x03(\v2$.tracee.v1beta1.datastores.DataEntryR\aentries\"=\n" +
	"\x16WriteBatchDataResponse\x12#\n" +
	"\rwritten_count\x18\x01 \x01(\x05R\fwrittenCount\"r\n" +
	"\x11DeleteDataRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12&\n" +
	"\x03key\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03key\"\x14\n" +
	"\x12DeleteDataResponse\"K\n" +
	"\x12ClearSourceRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\":\n" +
	"\x13ClearSourceResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"3\n" +
	"\x12ListSourcesRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\"/\n" +
	"\x13ListSourcesResponse\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources2\xb8\x04\n" +
	"\x10DataStoreService\x12f\n" +
	"\tWriteData\x12+.tracee.v1beta1.datastores.WriteDataRequest\x1a,.tracee.v1beta1.datastores.WriteDataResponse\x12u\n" +
	"\x0eWriteBatchData\x120.tracee.v1beta1.datastores.WriteBatchDataRequest\x1a1.tracee.v1beta1.datastores.WriteBatchDataResponse\x12i\n" +
	"\n" +
	"DeleteData\x12,.tracee.v1beta1.datastores.DeleteDataRequest\x1a-.tracee.v1beta1.datastores.DeleteDataResponse\x12l\n" +
	"\vClearSource\x12-.tracee.v1beta1.datastores.ClearSourceRequest\x1a..tracee.v1beta1.datastores.ClearSourceResponse\x12l\n" +
	"\vListSources\x12-.tracee.v1beta1.datastores.ListSourcesRequest\x1a..tracee.v1beta1.datastores.ListSourcesResponseBBZ@github.com/aquasecurity/tracee/api/v1beta1/datastores;datastoresb\x06proto3"

var (
	file_api_v1beta1_datastores_writable_proto_rawDescOnce sync.Once
	file_api_v1beta1_datastores_writable_proto_rawDescData []byte
)

func file_api_v1beta1_datastores_writable_proto_rawDescGZIP() []byte {
	file_api_v1beta1_datastores_writable_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_datastores_writable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_datastores_writable_proto_rawDesc), len(file_api_v1beta1_datastores_writable_proto_rawDesc)))
	})
	return file_api_v1beta1_datastores_writable_proto_rawDescData
}

var file_api_v1beta1_datastores_writable_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1beta1_datastores_writable_proto_goTypes = []any{
	(*DataEntry)(nil),              // 0: tracee.v1beta1.datastores.DataEntry
	(*WriteDataRequest)(nil),       // 1: tracee.v1beta1.datastores.WriteDataRequest
	(*WriteDataResponse)(nil),      // 2: tracee.v1beta1.datastores.WriteDataResponse
	(*WriteBatchDataRequest)(nil),  // 3: tracee.v1beta1.datastores.WriteBatchDataRequest
	(*WriteBatchDataResponse)(nil), // 4: tracee.v1beta1.datastores.WriteBatchDataResponse
	(*DeleteDataRequest)(nil),      // 5: tracee.v1beta1.datastores.DeleteDataRequest
	(*DeleteDataResponse)(nil),     // 6: tracee.v1beta1.datastores.DeleteDataResponse
	(*ClearSourceRequest)(nil),     // 7: tracee.v1beta1.datastores.ClearSourceRequest
	(*ClearSourceResponse)(nil),    // 8: tracee.v1beta1.datastores.ClearSourceResponse
	(*ListSourcesRequest)(nil),     // 9: tracee.v1beta1.datastores.ListSourcesRequest
	(*ListSourcesResponse)(nil),    // 10: tracee.v1beta1.datastores.ListSourcesResponse
	(*anypb.Any)(nil),              // 11: google.protobuf.Any
}
var file_api_v1beta1_datastores_writable_proto_depIdxs = []int32{
	11, // 0: tracee.v1beta1.datastores.DataEntry.key:type_name -> google.protobuf.Any
	11, // 1: tracee.v1beta1.datastores.DataEntry.data:type_name -> google.protobuf.Any
	0,  // 2: tracee.v1beta1.datastores.WriteDataRequest.entry:type_name -> tracee.v1beta1.datastores.DataEntry
	0,  // 3: tracee.v1beta1.datastores.WriteBatchDataRequest.entries:type_name -> tracee.v1beta1.datastores.DataEntry
	11, // 4: tracee.v1beta1.datastores.DeleteDataRequest.key:type_name -> google.protobuf.Any
	1,  // 5: tracee.v1beta1.datastores.DataStoreService.WriteData:input_type -> tracee.v1beta1.datastores.WriteDataRequest
	3,  // 6: tracee.v1beta1.datastores.DataStoreService.WriteBatchData:input_type -> tracee.v1beta1.datastores.WriteBatchDataRequest
	5,  // 7: tracee.v1beta1.datastores.DataStoreService.DeleteData:input_type -> tracee.v1beta1.datastores.DeleteDataRequest
	7,  // 8: tracee.v1beta1.datastores.DataStoreService.ClearSource:input_type -> tracee.v1beta1.datastores.ClearSourceRequest
	9,  // 9: tracee.v1beta1.datastores.DataStoreService.ListSources:input_type -> tracee.v1beta1.datastores.ListSourcesRequest
	2,  // 10: tracee.v1beta1.datastores.DataStoreService.WriteData:output_type -> tracee.v1beta1.datastores.WriteDataResponse
	4,  // 11: tracee.v1beta1.datastores.DataStoreService.WriteBatchData:output_type -> tracee.v1beta1.datastores.WriteBatchDataResponse
	6,  // 12: tracee.v1beta1.datastores.DataStoreService.DeleteData:output_type -> tracee.v1beta1.datastores.DeleteDataResponse
	8,  // 13: tracee.v1beta1.datastores.DataStoreService.ClearSource:output_type -> tracee.v1beta1.datastores.ClearSourceResponse
	10, // 14: tracee.v1beta1.datastores.DataStoreService.ListSources:output_type -> tracee.v1beta1.datastores.ListSourcesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1beta1_datastores_writable_proto_init() }
func file_api_v1beta1_datastores_writable_proto_init() {
	if File_api_v1beta1_datastores_writable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_datastores_writable_proto_rawDesc), len(file_api_v1beta1_datastores_writable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta1_datastores_writable_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_datastores_writable_proto_depIdxs,
		MessageInfos:      file_api_v1beta1_datastores_writable_proto_msgTypes,
	}.Build()
	File_api_v1beta1_datastores_writable_proto = out.File
	file_api_v1beta1_datastores_writable_proto_goTypes = nil
	file_api_v1beta1_datastores_writable_proto_depIdxs = nil
}
