name: Run E2E Tests
description: |
  Run end-to-end tests including compatibility, core, network, and kernel tests.
  Build dependencies are handled automatically by make rules.
  Handles test failure detection and artifact uploads.
inputs:
  job-name:
    description: 'Job name for artifact naming'
    required: true
  run-id:
    description: 'GitHub run ID for artifact naming'
    required: true
  run-attempt:
    description: 'GitHub run attempt for artifact naming'
    required: true
runs:
  using: composite
  steps:
    - name: Compatibility Test
      run: env "PATH=$PATH" make test-compatibility
      shell: bash
    - name: E2E Test (Core and Extended)
      id: e2e-test
      run: |
        make test-e2e E2E_ARGS="--keep-artifacts" 2>&1 | tee /tmp/e2e-test.log
        exit ${PIPESTATUS[0]}
      shell: bash
    - name: E2E Network Test
      id: e2e-net-test
      run: |
        make test-e2e-net E2E_ARGS="--keep-artifacts" 2>&1 | tee /tmp/e2e-test-net.log
        exit ${PIPESTATUS[0]}
      shell: bash
    - name: E2E Kernel Test
      id: e2e-kernel-test
      run: |
        make test-e2e-kernel E2E_ARGS="--keep-artifacts" 2>&1 | tee /tmp/e2e-test-kernel.log
        exit ${PIPESTATUS[0]}
      shell: bash
    - name: Determine Failed Test
      id: failed-test
      if: failure() && (
        steps.e2e-test.conclusion == 'failure' ||
        steps.e2e-net-test.conclusion == 'failure' || 
        steps.e2e-kernel-test.conclusion == 'failure'
        )
      run: |
        if [[ "${{ steps.e2e-test.conclusion }}" == "failure" ]]; then
          echo "name=e2e" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.e2e-net-test.conclusion }}" == "failure" ]]; then
          echo "name=net" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.e2e-kernel-test.conclusion }}" == "failure" ]]; then
          echo "name=kernel" >> $GITHUB_OUTPUT
        else
          echo "No failed tests. Should not reach this point."
          exit 1
        fi
      shell: bash
    - name: Upload E2E Test Artifacts
      if: always() && steps.failed-test.outputs.name != ''
      uses: actions/upload-artifact@v4
      with:
        name: e2e-${{ steps.failed-test.outputs.name }}-artifacts-${{ inputs.job-name }}-${{ inputs.run-id }}-${{ inputs.run-attempt }}
        path: |
          /tmp/tracee-log-*
          /tmp/tracee-output-*
          /tmp/e2e-*.log
        retention-days: 7
        if-no-files-found: warn
    - name: Notify About Available E2E Test Artifacts
      if: always() && steps.failed-test.outputs.name != ''
      run: |
        echo "::notice title=Debug Artifacts Available::E2E tests failed. Debug artifacts have been uploaded and can be downloaded from the Summary tab. Look for: e2e-${{ steps.failed-test.outputs.name }}-artifacts-${{ inputs.job-name }}-${{ inputs.run-id }}-${{ inputs.run-attempt }}"
        echo ""
        echo "ðŸ“‹ **E2E Test Failed - Debug Information Available**"
        echo ""
        echo "ðŸ” **How to access debug artifacts:**"
        echo "1. Click on the 'Summary' tab above the jobs list"
        echo "2. Scroll to the bottom of the Summary page"
        echo "3. Look for the 'Artifacts' section"
        echo "4. Download: \`e2e-${{ steps.failed-test.outputs.name }}-artifacts-${{ inputs.job-name }}-${{ inputs.run-id }}-${{ inputs.run-attempt }}\`"
        echo ""
        echo "ðŸ“ **What's included in the artifacts:**"
        echo "- **Log file**: Full debug-level logs from all E2E tests (tracee-log-*)"
        echo "- **Output file**: JSON events captured during all E2E tests (tracee-output-*)"
        echo "- **Pipeline log**: Complete stdout/stderr from the failed test (e2e-*.log)"
        echo ""
        echo "âš ï¸ **Note**: Artifacts are available for 7 days from upload"
      shell: bash
    - name: Cleanup E2E Test Artifacts
      if: always()
      run: |
        # Clean up artifact files from runner filesystem
        rm -f /tmp/tracee-log-* /tmp/tracee-output-* /tmp/e2e-*.log 2>/dev/null || true
        echo "Cleaned up local artifact files from all E2E tests"
      shell: bash

