// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: types/api/v1beta1/tracee.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sets      []string `protobuf:"bytes,2,rep,name=sets,proto3" json:"sets,omitempty"`
	Arguments []string `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"` // TODO: perhaps metadata should be part of the definition
}

func (x *EventDefinition) Reset() {
	*x = EventDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_api_v1beta1_tracee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDefinition) ProtoMessage() {}

func (x *EventDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_types_api_v1beta1_tracee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDefinition.ProtoReflect.Descriptor instead.
func (*EventDefinition) Descriptor() ([]byte, []int) {
	return file_types_api_v1beta1_tracee_proto_rawDescGZIP(), []int{0}
}

func (x *EventDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventDefinition) GetSets() []string {
	if x != nil {
		return x.Sets
	}
	return nil
}

func (x *EventDefinition) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ListEventDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEventDefinitionRequest) Reset() {
	*x = ListEventDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_api_v1beta1_tracee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEventDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventDefinitionRequest) ProtoMessage() {}

func (x *ListEventDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_api_v1beta1_tracee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ListEventDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_types_api_v1beta1_tracee_proto_rawDescGZIP(), []int{1}
}

type ListEventDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*EventDefinition `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ListEventDefinitionResponse) Reset() {
	*x = ListEventDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_api_v1beta1_tracee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEventDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventDefinitionResponse) ProtoMessage() {}

func (x *ListEventDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_api_v1beta1_tracee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventDefinitionResponse.ProtoReflect.Descriptor instead.
func (*ListEventDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_types_api_v1beta1_tracee_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventDefinitionResponse) GetEvents() []*EventDefinition {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_types_api_v1beta1_tracee_proto protoreflect.FileDescriptor

var file_types_api_v1beta1_tracee_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x22, 0x57, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x32,
	0x7b, 0x0a, 0x06, 0x54, 0x72, 0x61, 0x63, 0x65, 0x65, 0x12, 0x71, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x2a, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x2f, 0x61, 0x71, 0x75, 0x61, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_types_api_v1beta1_tracee_proto_rawDescOnce sync.Once
	file_types_api_v1beta1_tracee_proto_rawDescData = file_types_api_v1beta1_tracee_proto_rawDesc
)

func file_types_api_v1beta1_tracee_proto_rawDescGZIP() []byte {
	file_types_api_v1beta1_tracee_proto_rawDescOnce.Do(func() {
		file_types_api_v1beta1_tracee_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_api_v1beta1_tracee_proto_rawDescData)
	})
	return file_types_api_v1beta1_tracee_proto_rawDescData
}

var file_types_api_v1beta1_tracee_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_api_v1beta1_tracee_proto_goTypes = []interface{}{
	(*EventDefinition)(nil),             // 0: tracee.v1beta1.EventDefinition
	(*ListEventDefinitionRequest)(nil),  // 1: tracee.v1beta1.ListEventDefinitionRequest
	(*ListEventDefinitionResponse)(nil), // 2: tracee.v1beta1.ListEventDefinitionResponse
}
var file_types_api_v1beta1_tracee_proto_depIdxs = []int32{
	0, // 0: tracee.v1beta1.ListEventDefinitionResponse.events:type_name -> tracee.v1beta1.EventDefinition
	1, // 1: tracee.v1beta1.Tracee.ListEventDefinitions:input_type -> tracee.v1beta1.ListEventDefinitionRequest
	2, // 2: tracee.v1beta1.Tracee.ListEventDefinitions:output_type -> tracee.v1beta1.ListEventDefinitionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_api_v1beta1_tracee_proto_init() }
func file_types_api_v1beta1_tracee_proto_init() {
	if File_types_api_v1beta1_tracee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_api_v1beta1_tracee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_api_v1beta1_tracee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEventDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_api_v1beta1_tracee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEventDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_api_v1beta1_tracee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_types_api_v1beta1_tracee_proto_goTypes,
		DependencyIndexes: file_types_api_v1beta1_tracee_proto_depIdxs,
		MessageInfos:      file_types_api_v1beta1_tracee_proto_msgTypes,
	}.Build()
	File_types_api_v1beta1_tracee_proto = out.File
	file_types_api_v1beta1_tracee_proto_rawDesc = nil
	file_types_api_v1beta1_tracee_proto_goTypes = nil
	file_types_api_v1beta1_tracee_proto_depIdxs = nil
}
