{
 "title": "TRACEE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(tracee_events_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_events_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Filtered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(tracee_events_filtered[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_events_filtered  {job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered/Total ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_events_total", "legendFormat": "__auto" },
    { "expr": "tracee_events_filtered", "legendFormat": "__auto" },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Lost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(tracee_lostevents_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_lostevents_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost/Total ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_events_total", "legendFormat": "__auto" },
    { "expr": "tracee_lostevents_total", "legendFormat": "__auto" },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Perf Event Buffer (METRICS=1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Submit Attempts",
     "type": "bargauge",
     "gridPos": { "h": 38, "w": 8, "x": 0, "y": 1326 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tracee_bpf_perf_event_submit_attempts",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Submit Failures",
     "type": "bargauge",
     "gridPos": { "h": 38, "w": 8, "x": 8, "y": 1326 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tracee_bpf_perf_event_submit_failures",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Failures Ratio",
     "type": "bargauge",
     "gridPos": { "h": 38, "w": 8, "x": 16, "y": 1326 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tracee_bpf_perf_event_submit_failures/tracee_bpf_perf_event_submit_attempts",
       "legendFormat": "{{event_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time (Tracee)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(process_cpu_seconds_total{job=\"tracee\"}[$__rate_interval]) * 100)\n/\non()\ncount(node_cpu_seconds_total{mode=\"idle\"})",
       "legendFormat": "Tracee"
      }
     ]
    },
    {
     "title": "CPU Time (Tracee - Avg %)",
     "type": "stat",
     "description": "Measures the average percentage of CPU time used by the Tracee process relative to the total number of CPU cores available.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{job=\"tracee\"}[$__rate_interval]) * 100)\n/\ncount(node_cpu_seconds_total{mode=\"idle\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Time (All but idle/Tracee)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))) * 100",
       "legendFormat": "All but idle"
      },
      {
       "expr": "(rate(process_cpu_seconds_total{job=\"tracee\"}[$__rate_interval]) * 100)\n/\non()\ncount(node_cpu_seconds_total{mode=\"idle\"})",
       "legendFormat": "Tracee"
      }
     ]
    },
    {
     "title": "CPU Time Share (Tracee vs Non-Idle)",
     "type": "stat",
     "description": "Average ratio of CPU usage by the Tracee process compared to the total non-idle CPU usage on the system.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  (rate(process_cpu_seconds_total{job=\"tracee\"}[$__rate_interval]))\n  /\n  on()\n  count(node_cpu_seconds_total{mode=\"idle\"})\n)\n/\n(\n  1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Malloc Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"tracee\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Malloc Rate (avg)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"tracee\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Malloc Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free/Malloc ratio",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 21, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"tracee\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_frees_total{job=\"tracee\"}",
       "legendFormat": "__auto"
      },
      { "expression": "$B/$A", "type": "math" }
     ]
    },
    {
     "title": "Free Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 240 },
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{job=\"tracee\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Rate (avg)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{job=\"tracee\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_frees_total{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"tracee\"}",
       "legendFormat": "in use"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"tracee\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"tracee\"}",
       "legendFormat": "released"
      }
     ]
    },
    {
     "title": "Heap In Use (avg)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Objects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Objects (avg)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pressure Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Pressure Data (avg)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=\"tracee\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Pressure Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"tracee\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Pressure Time (avg)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"tracee\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time (All but idle - per core)",
     "type": "timeseries",
     "description": "Each line represents ONE SPECIFIC CPU percentage.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "CPU Time (All but idle - avg)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))) * 100",
       "legendFormat": "All but idle"
      }
     ]
    },
    {
     "title": "Memory (GB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes/1024/1024/1024",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "node_memory_MemFree_bytes/1024/1024/1024",
       "legendFormat": "FREE"
      },
      {
       "expr": "(node_memory_SReclaimable_bytes+node_memory_KReclaimable_bytes)/1024/1024/1024",
       "legendFormat": "RECLAIMABLE"
      },
      {
       "expr": "node_memory_Active_bytes/1024/1024/1024",
       "legendFormat": "ACTIVE"
      },
      {
       "expr": "node_memory_Inactive_bytes/1024/1024/1024",
       "legendFormat": "INACTIVE"
      },
      {
       "expr": "(node_memory_Cached_bytes+node_memory_Buffers_bytes)/1024/1024/1024",
       "legendFormat": "FS CACHE + BUFFERS"
      }
     ]
    }
   ]
  }
 ]
}