name: Build Dependencies
description: |
  Install build dependencies to test and compile tracee artifacts
inputs:
  # set default versions in a single place (as default)
  clang-version:
    description: clang version
    default: "14"
  go-version:
    description: go version
    required: true
    default: "1.19.5"
  opa-version:
    description: opa version
    required: true
    default: "v0.48.0"
runs:
  using: composite
  steps:
    - name: Install Base Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y bsdutils build-essential pkgconf
        sudo apt-get install -y zlib1g-dev libelf-dev
        sudo apt-get install -y software-properties-common
      shell: bash
    - name: Install Clang
      run: |
        curl -L -o /tmp/llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 755 /tmp/llvm.sh
        sudo /tmp/llvm.sh ${{ inputs.clang-version }}
        sudo update-alternatives --remove-all clang || true
        sudo update-alternatives --remove-all llc || true
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ inputs.clang-version }} 1
        sudo update-alternatives --install /usr/bin/llc llc /usr/bin/llc-${{ inputs.clang-version }} 1
      shell: bash
    - name: Install Golang
      run: |
        curl -L -o /tmp/go.tar.xz https://go.dev/dl/go${{ inputs.go-version }}.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go.tar.xz
        sudo update-alternatives --remove-all go || true
        sudo update-alternatives --remove-all gofmt || true
        sudo update-alternatives --install /usr/bin/go go /usr/local/go/bin/go 1
        sudo update-alternatives --install /usr/bin/gofmt gofmt /usr/local/go/bin/gofmt 1
      shell: bash
    - name: Install OPA
      run: |
        sudo curl -L -o /usr/bin/opa https://github.com/open-policy-agent/opa/releases/download/${{ inputs.opa-version }}/opa_linux_amd64
        sudo chmod 755 /usr/bin/opa
      shell: bash
    - name: Install staticchecker
      run: |
        GOROOT=/usr/local/go GOPATH=$HOME/go go install honnef.co/go/tools/cmd/staticcheck@latest
        sudo cp $HOME/go/bin/staticcheck /usr/bin/
      shell: bash
    - name: Install docker
      run: |
        sudo apt-get install --yes ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get --yes update
        sudo apt-get install --yes docker-ce docker-ce-cli containerd.io
      shell: bash