// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/datasource.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           *structpb.Value        `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataSourceRequest) Reset() {
	*x = WriteDataSourceRequest{}
	mi := &file_api_v1beta1_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataSourceRequest) ProtoMessage() {}

func (x *WriteDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataSourceRequest.ProtoReflect.Descriptor instead.
func (*WriteDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *WriteDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteDataSourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WriteDataSourceRequest) GetKey() *structpb.Value {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WriteDataSourceRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteDataSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataSourceResponse) Reset() {
	*x = WriteDataSourceResponse{}
	mi := &file_api_v1beta1_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataSourceResponse) ProtoMessage() {}

func (x *WriteDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataSourceResponse.ProtoReflect.Descriptor instead.
func (*WriteDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_datasource_proto_rawDescGZIP(), []int{1}
}

var File_api_v1beta1_datasource_proto protoreflect.FileDescriptor

const file_api_v1beta1_datasource_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1beta1/datasource.proto\x12\x0etracee.v1beta1\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\x01\n" +
	"\x16WriteDataSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12(\n" +
	"\x03key\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x03key\x12,\n" +
	"\x05value\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\x19\n" +
	"\x17WriteDataSourceResponse2\xcf\x01\n" +
	"\x11DataSourceService\x12X\n" +
	"\x05Write\x12&.tracee.v1beta1.WriteDataSourceRequest\x1a'.tracee.v1beta1.WriteDataSourceResponse\x12`\n" +
	"\vWriteStream\x12&.tracee.v1beta1.WriteDataSourceRequest\x1a'.tracee.v1beta1.WriteDataSourceResponse(\x01B+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_datasource_proto_rawDescOnce sync.Once
	file_api_v1beta1_datasource_proto_rawDescData []byte
)

func file_api_v1beta1_datasource_proto_rawDescGZIP() []byte {
	file_api_v1beta1_datasource_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_datasource_proto_rawDesc), len(file_api_v1beta1_datasource_proto_rawDesc)))
	})
	return file_api_v1beta1_datasource_proto_rawDescData
}

var file_api_v1beta1_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1beta1_datasource_proto_goTypes = []any{
	(*WriteDataSourceRequest)(nil),  // 0: tracee.v1beta1.WriteDataSourceRequest
	(*WriteDataSourceResponse)(nil), // 1: tracee.v1beta1.WriteDataSourceResponse
	(*structpb.Value)(nil),          // 2: google.protobuf.Value
}
var file_api_v1beta1_datasource_proto_depIdxs = []int32{
	2, // 0: tracee.v1beta1.WriteDataSourceRequest.key:type_name -> google.protobuf.Value
	2, // 1: tracee.v1beta1.WriteDataSourceRequest.value:type_name -> google.protobuf.Value
	0, // 2: tracee.v1beta1.DataSourceService.Write:input_type -> tracee.v1beta1.WriteDataSourceRequest
	0, // 3: tracee.v1beta1.DataSourceService.WriteStream:input_type -> tracee.v1beta1.WriteDataSourceRequest
	1, // 4: tracee.v1beta1.DataSourceService.Write:output_type -> tracee.v1beta1.WriteDataSourceResponse
	1, // 5: tracee.v1beta1.DataSourceService.WriteStream:output_type -> tracee.v1beta1.WriteDataSourceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1beta1_datasource_proto_init() }
func file_api_v1beta1_datasource_proto_init() {
	if File_api_v1beta1_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_datasource_proto_rawDesc), len(file_api_v1beta1_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta1_datasource_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_datasource_proto_depIdxs,
		MessageInfos:      file_api_v1beta1_datasource_proto_msgTypes,
	}.Build()
	File_api_v1beta1_datasource_proto = out.File
	file_api_v1beta1_datasource_proto_goTypes = nil
	file_api_v1beta1_datasource_proto_depIdxs = nil
}
