// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/definition.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventField) Reset() {
	*x = EventField{}
	mi := &file_api_v1beta1_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventField) ProtoMessage() {}

func (x *EventField) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventField.ProtoReflect.Descriptor instead.
func (*EventField) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_definition_proto_rawDescGZIP(), []int{0}
}

func (x *EventField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EventDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Fields        []*EventField          `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDefinition) Reset() {
	*x = EventDefinition{}
	mi := &file_api_v1beta1_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDefinition) ProtoMessage() {}

func (x *EventDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDefinition.ProtoReflect.Descriptor instead.
func (*EventDefinition) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_definition_proto_rawDescGZIP(), []int{1}
}

func (x *EventDefinition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventDefinition) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *EventDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventDefinition) GetFields() []*EventField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint64                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint64                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint64                 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_api_v1beta1_definition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_definition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_definition_proto_rawDescGZIP(), []int{2}
}

func (x *Version) GetMajor() uint64 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() uint64 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() uint64 {
	if x != nil {
		return x.Patch
	}
	return 0
}

var File_api_v1beta1_definition_proto protoreflect.FileDescriptor

const file_api_v1beta1_definition_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1beta1/definition.proto\x12\x0etracee.v1beta1\"4\n" +
	"\n" +
	"EventField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xd2\x01\n" +
	"\x0fEventDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\aversion\x18\x03 \x01(\v2\x17.tracee.v1beta1.VersionR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x122\n" +
	"\x06fields\x18\x06 \x03(\v2\x1a.tracee.v1beta1.EventFieldR\x06fields\"K\n" +
	"\aVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x04R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x04R\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\x04R\x05patchB+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_definition_proto_rawDescOnce sync.Once
	file_api_v1beta1_definition_proto_rawDescData []byte
)

func file_api_v1beta1_definition_proto_rawDescGZIP() []byte {
	file_api_v1beta1_definition_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_definition_proto_rawDesc), len(file_api_v1beta1_definition_proto_rawDesc)))
	})
	return file_api_v1beta1_definition_proto_rawDescData
}

var file_api_v1beta1_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1beta1_definition_proto_goTypes = []any{
	(*EventField)(nil),      // 0: tracee.v1beta1.EventField
	(*EventDefinition)(nil), // 1: tracee.v1beta1.EventDefinition
	(*Version)(nil),         // 2: tracee.v1beta1.Version
}
var file_api_v1beta1_definition_proto_depIdxs = []int32{
	2, // 0: tracee.v1beta1.EventDefinition.version:type_name -> tracee.v1beta1.Version
	0, // 1: tracee.v1beta1.EventDefinition.fields:type_name -> tracee.v1beta1.EventField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1beta1_definition_proto_init() }
func file_api_v1beta1_definition_proto_init() {
	if File_api_v1beta1_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_definition_proto_rawDesc), len(file_api_v1beta1_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1beta1_definition_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_definition_proto_depIdxs,
		MessageInfos:      file_api_v1beta1_definition_proto_msgTypes,
	}.Build()
	File_api_v1beta1_definition_proto = out.File
	file_api_v1beta1_definition_proto_goTypes = nil
	file_api_v1beta1_definition_proto_depIdxs = nil
}
