// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/detector_catalog.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectorCatalogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorId    string                 `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	DetectorName  string                 `protobuf:"bytes,2,opt,name=detector_name,json=detectorName,proto3" json:"detector_name,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Version       *Version               `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorCatalogEntry) Reset() {
	*x = DetectorCatalogEntry{}
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorCatalogEntry) ProtoMessage() {}

func (x *DetectorCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorCatalogEntry.ProtoReflect.Descriptor instead.
func (*DetectorCatalogEntry) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_detector_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *DetectorCatalogEntry) GetDetectorId() string {
	if x != nil {
		return x.DetectorId
	}
	return ""
}

func (x *DetectorCatalogEntry) GetDetectorName() string {
	if x != nil {
		return x.DetectorName
	}
	return ""
}

func (x *DetectorCatalogEntry) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DetectorCatalogEntry) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DetectorCatalogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectorCatalogEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetectorCatalogEntry) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GetDetectorsCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorIds   []string               `protobuf:"bytes,1,rep,name=detector_ids,json=detectorIds,proto3" json:"detector_ids,omitempty"`
	EventNames    []string               `protobuf:"bytes,2,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetectorsCatalogRequest) Reset() {
	*x = GetDetectorsCatalogRequest{}
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetectorsCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectorsCatalogRequest) ProtoMessage() {}

func (x *GetDetectorsCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectorsCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetDetectorsCatalogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_detector_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetDetectorsCatalogRequest) GetDetectorIds() []string {
	if x != nil {
		return x.DetectorIds
	}
	return nil
}

func (x *GetDetectorsCatalogRequest) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

type GetDetectorsCatalogResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*DetectorCatalogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetectorsCatalogResponse) Reset() {
	*x = GetDetectorsCatalogResponse{}
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetectorsCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectorsCatalogResponse) ProtoMessage() {}

func (x *GetDetectorsCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_detector_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectorsCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetDetectorsCatalogResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_detector_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetDetectorsCatalogResponse) GetEntries() []*DetectorCatalogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_v1beta1_detector_catalog_proto protoreflect.FileDescriptor

const file_api_v1beta1_detector_catalog_proto_rawDesc = "" +
	"\n" +
	"\"api/v1beta1/detector_catalog.proto\x12\x0etracee.v1beta1\x1a\x1capi/v1beta1/definition.proto\"\xf9\x02\n" +
	"\x14DetectorCatalogEntry\x12\x1f\n" +
	"\vdetector_id\x18\x01 \x01(\tR\n" +
	"detectorId\x12#\n" +
	"\rdetector_name\x18\x02 \x01(\tR\fdetectorName\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x121\n" +
	"\aversion\x18\x04 \x01(\v2\x17.tracee.v1beta1.VersionR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12T\n" +
	"\n" +
	"properties\x18\a \x03(\v24.tracee.v1beta1.DetectorCatalogEntry.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x1aGetDetectorsCatalogRequest\x12!\n" +
	"\fdetector_ids\x18\x01 \x03(\tR\vdetectorIds\x12\x1f\n" +
	"\vevent_names\x18\x02 \x03(\tR\n" +
	"eventNames\"]\n" +
	"\x1bGetDetectorsCatalogResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.tracee.v1beta1.DetectorCatalogEntryR\aentriesB+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_detector_catalog_proto_rawDescOnce sync.Once
	file_api_v1beta1_detector_catalog_proto_rawDescData []byte
)

func file_api_v1beta1_detector_catalog_proto_rawDescGZIP() []byte {
	file_api_v1beta1_detector_catalog_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_detector_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_detector_catalog_proto_rawDesc), len(file_api_v1beta1_detector_catalog_proto_rawDesc)))
	})
	return file_api_v1beta1_detector_catalog_proto_rawDescData
}

var file_api_v1beta1_detector_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1beta1_detector_catalog_proto_goTypes = []any{
	(*DetectorCatalogEntry)(nil),        // 0: tracee.v1beta1.DetectorCatalogEntry
	(*GetDetectorsCatalogRequest)(nil),  // 1: tracee.v1beta1.GetDetectorsCatalogRequest
	(*GetDetectorsCatalogResponse)(nil), // 2: tracee.v1beta1.GetDetectorsCatalogResponse
	nil,                                 // 3: tracee.v1beta1.DetectorCatalogEntry.PropertiesEntry
	(*Version)(nil),                     // 4: tracee.v1beta1.Version
}
var file_api_v1beta1_detector_catalog_proto_depIdxs = []int32{
	4, // 0: tracee.v1beta1.DetectorCatalogEntry.version:type_name -> tracee.v1beta1.Version
	3, // 1: tracee.v1beta1.DetectorCatalogEntry.properties:type_name -> tracee.v1beta1.DetectorCatalogEntry.PropertiesEntry
	0, // 2: tracee.v1beta1.GetDetectorsCatalogResponse.entries:type_name -> tracee.v1beta1.DetectorCatalogEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1beta1_detector_catalog_proto_init() }
func file_api_v1beta1_detector_catalog_proto_init() {
	if File_api_v1beta1_detector_catalog_proto != nil {
		return
	}
	file_api_v1beta1_definition_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_detector_catalog_proto_rawDesc), len(file_api_v1beta1_detector_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1beta1_detector_catalog_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_detector_catalog_proto_depIdxs,
		MessageInfos:      file_api_v1beta1_detector_catalog_proto_msgTypes,
	}.Build()
	File_api_v1beta1_detector_catalog_proto = out.File
	file_api_v1beta1_detector_catalog_proto_goTypes = nil
	file_api_v1beta1_detector_catalog_proto_depIdxs = nil
}
