// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/diagnostic.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_Debug  LogLevel = 0
	LogLevel_Info   LogLevel = 1
	LogLevel_Warn   LogLevel = 2
	LogLevel_Error  LogLevel = 3
	LogLevel_DPanic LogLevel = 4
	LogLevel_Panic  LogLevel = 5
	LogLevel_Fatal  LogLevel = 6
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
		4: "DPanic",
		5: "Panic",
		6: "Fatal",
	}
	LogLevel_value = map[string]int32{
		"Debug":  0,
		"Info":   1,
		"Warn":   2,
		"Error":  3,
		"DPanic": 4,
		"Panic":  5,
		"Fatal":  6,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1beta1_diagnostic_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_v1beta1_diagnostic_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{0}
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{0}
}

type GetMetricsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventCount       uint64                 `protobuf:"varint,1,opt,name=EventCount,proto3" json:"EventCount,omitempty"`
	EventsFiltered   uint64                 `protobuf:"varint,2,opt,name=EventsFiltered,proto3" json:"EventsFiltered,omitempty"`
	NetCapCount      uint64                 `protobuf:"varint,3,opt,name=NetCapCount,proto3" json:"NetCapCount,omitempty"`
	BPFLogsCount     uint64                 `protobuf:"varint,4,opt,name=BPFLogsCount,proto3" json:"BPFLogsCount,omitempty"`
	ErrorCount       uint64                 `protobuf:"varint,5,opt,name=ErrorCount,proto3" json:"ErrorCount,omitempty"`
	LostEvCount      uint64                 `protobuf:"varint,6,opt,name=LostEvCount,proto3" json:"LostEvCount,omitempty"`
	LostWrCount      uint64                 `protobuf:"varint,7,opt,name=LostWrCount,proto3" json:"LostWrCount,omitempty"`
	LostNtCapCount   uint64                 `protobuf:"varint,8,opt,name=LostNtCapCount,proto3" json:"LostNtCapCount,omitempty"`
	LostBPFLogsCount uint64                 `protobuf:"varint,9,opt,name=LostBPFLogsCount,proto3" json:"LostBPFLogsCount,omitempty"`
	BPFEventStats    []*BPFEventStats       `protobuf:"bytes,10,rep,name=BPFEventStats,proto3" json:"BPFEventStats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsResponse) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *GetMetricsResponse) GetEventsFiltered() uint64 {
	if x != nil {
		return x.EventsFiltered
	}
	return 0
}

func (x *GetMetricsResponse) GetNetCapCount() uint64 {
	if x != nil {
		return x.NetCapCount
	}
	return 0
}

func (x *GetMetricsResponse) GetBPFLogsCount() uint64 {
	if x != nil {
		return x.BPFLogsCount
	}
	return 0
}

func (x *GetMetricsResponse) GetErrorCount() uint64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *GetMetricsResponse) GetLostEvCount() uint64 {
	if x != nil {
		return x.LostEvCount
	}
	return 0
}

func (x *GetMetricsResponse) GetLostWrCount() uint64 {
	if x != nil {
		return x.LostWrCount
	}
	return 0
}

func (x *GetMetricsResponse) GetLostNtCapCount() uint64 {
	if x != nil {
		return x.LostNtCapCount
	}
	return 0
}

func (x *GetMetricsResponse) GetLostBPFLogsCount() uint64 {
	if x != nil {
		return x.LostBPFLogsCount
	}
	return 0
}

func (x *GetMetricsResponse) GetBPFEventStats() []*BPFEventStats {
	if x != nil {
		return x.BPFEventStats
	}
	return nil
}

type BPFEventStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            EventId                `protobuf:"varint,1,opt,name=id,proto3,enum=tracee.v1beta1.EventId" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Internal      bool                   `protobuf:"varint,3,opt,name=internal,proto3" json:"internal,omitempty"`
	Attempts      uint64                 `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Failures      uint64                 `protobuf:"varint,5,opt,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BPFEventStats) Reset() {
	*x = BPFEventStats{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFEventStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFEventStats) ProtoMessage() {}

func (x *BPFEventStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFEventStats.ProtoReflect.Descriptor instead.
func (*BPFEventStats) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{2}
}

func (x *BPFEventStats) GetId() EventId {
	if x != nil {
		return x.Id
	}
	return EventId_unspecified
}

func (x *BPFEventStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BPFEventStats) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *BPFEventStats) GetAttempts() uint64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *BPFEventStats) GetFailures() uint64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

type ChangeLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=tracee.v1beta1.LogLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeLogLevelRequest) Reset() {
	*x = ChangeLogLevelRequest{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLogLevelRequest) ProtoMessage() {}

func (x *ChangeLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLogLevelRequest.ProtoReflect.Descriptor instead.
func (*ChangeLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeLogLevelRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Debug
}

type ChangeLogLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeLogLevelResponse) Reset() {
	*x = ChangeLogLevelResponse{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLogLevelResponse) ProtoMessage() {}

func (x *ChangeLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLogLevelResponse.ProtoReflect.Descriptor instead.
func (*ChangeLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{4}
}

type GetStacktraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStacktraceRequest) Reset() {
	*x = GetStacktraceRequest{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStacktraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStacktraceRequest) ProtoMessage() {}

func (x *GetStacktraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStacktraceRequest.ProtoReflect.Descriptor instead.
func (*GetStacktraceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{5}
}

type GetStacktraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stacktrace    []byte                 `protobuf:"bytes,1,opt,name=Stacktrace,proto3" json:"Stacktrace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStacktraceResponse) Reset() {
	*x = GetStacktraceResponse{}
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStacktraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStacktraceResponse) ProtoMessage() {}

func (x *GetStacktraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_diagnostic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStacktraceResponse.ProtoReflect.Descriptor instead.
func (*GetStacktraceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_diagnostic_proto_rawDescGZIP(), []int{6}
}

func (x *GetStacktraceResponse) GetStacktrace() []byte {
	if x != nil {
		return x.Stacktrace
	}
	return nil
}

var File_api_v1beta1_diagnostic_proto protoreflect.FileDescriptor

const file_api_v1beta1_diagnostic_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1beta1/diagnostic.proto\x12\x0etracee.v1beta1\x1a\x17api/v1beta1/event.proto\"\x13\n" +
	"\x11GetMetricsRequest\"\x9f\x03\n" +
	"\x12GetMetricsResponse\x12\x1e\n" +
	"\n" +
	"EventCount\x18\x01 \x01(\x04R\n" +
	"EventCount\x12&\n" +
	"\x0eEventsFiltered\x18\x02 \x01(\x04R\x0eEventsFiltered\x12 \n" +
	"\vNetCapCount\x18\x03 \x01(\x04R\vNetCapCount\x12\"\n" +
	"\fBPFLogsCount\x18\x04 \x01(\x04R\fBPFLogsCount\x12\x1e\n" +
	"\n" +
	"ErrorCount\x18\x05 \x01(\x04R\n" +
	"ErrorCount\x12 \n" +
	"\vLostEvCount\x18\x06 \x01(\x04R\vLostEvCount\x12 \n" +
	"\vLostWrCount\x18\a \x01(\x04R\vLostWrCount\x12&\n" +
	"\x0eLostNtCapCount\x18\b \x01(\x04R\x0eLostNtCapCount\x12*\n" +
	"\x10LostBPFLogsCount\x18\t \x01(\x04R\x10LostBPFLogsCount\x12C\n" +
	"\rBPFEventStats\x18\n" +
	" \x03(\v2\x1d.tracee.v1beta1.BPFEventStatsR\rBPFEventStats\"\xa0\x01\n" +
	"\rBPFEventStats\x12'\n" +
	"\x02id\x18\x01 \x01(\x0e2\x17.tracee.v1beta1.EventIdR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\binternal\x18\x03 \x01(\bR\binternal\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x04R\battempts\x12\x1a\n" +
	"\bfailures\x18\x05 \x01(\x04R\bfailures\"G\n" +
	"\x15ChangeLogLevelRequest\x12.\n" +
	"\x05level\x18\x01 \x01(\x0e2\x18.tracee.v1beta1.LogLevelR\x05level\"\x18\n" +
	"\x16ChangeLogLevelResponse\"\x16\n" +
	"\x14GetStacktraceRequest\"7\n" +
	"\x15GetStacktraceResponse\x12\x1e\n" +
	"\n" +
	"Stacktrace\x18\x01 \x01(\fR\n" +
	"Stacktrace*V\n" +
	"\bLogLevel\x12\t\n" +
	"\x05Debug\x10\x00\x12\b\n" +
	"\x04Info\x10\x01\x12\b\n" +
	"\x04Warn\x10\x02\x12\t\n" +
	"\x05Error\x10\x03\x12\n" +
	"\n" +
	"\x06DPanic\x10\x04\x12\t\n" +
	"\x05Panic\x10\x05\x12\t\n" +
	"\x05Fatal\x10\x062\xa7\x02\n" +
	"\x11DiagnosticService\x12S\n" +
	"\n" +
	"GetMetrics\x12!.tracee.v1beta1.GetMetricsRequest\x1a\".tracee.v1beta1.GetMetricsResponse\x12_\n" +
	"\x0eChangeLogLevel\x12%.tracee.v1beta1.ChangeLogLevelRequest\x1a&.tracee.v1beta1.ChangeLogLevelResponse\x12\\\n" +
	"\rGetStacktrace\x12$.tracee.v1beta1.GetStacktraceRequest\x1a%.tracee.v1beta1.GetStacktraceResponseB+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_diagnostic_proto_rawDescOnce sync.Once
	file_api_v1beta1_diagnostic_proto_rawDescData []byte
)

func file_api_v1beta1_diagnostic_proto_rawDescGZIP() []byte {
	file_api_v1beta1_diagnostic_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_diagnostic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_diagnostic_proto_rawDesc), len(file_api_v1beta1_diagnostic_proto_rawDesc)))
	})
	return file_api_v1beta1_diagnostic_proto_rawDescData
}

var file_api_v1beta1_diagnostic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1beta1_diagnostic_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1beta1_diagnostic_proto_goTypes = []any{
	(LogLevel)(0),                  // 0: tracee.v1beta1.LogLevel
	(*GetMetricsRequest)(nil),      // 1: tracee.v1beta1.GetMetricsRequest
	(*GetMetricsResponse)(nil),     // 2: tracee.v1beta1.GetMetricsResponse
	(*BPFEventStats)(nil),          // 3: tracee.v1beta1.BPFEventStats
	(*ChangeLogLevelRequest)(nil),  // 4: tracee.v1beta1.ChangeLogLevelRequest
	(*ChangeLogLevelResponse)(nil), // 5: tracee.v1beta1.ChangeLogLevelResponse
	(*GetStacktraceRequest)(nil),   // 6: tracee.v1beta1.GetStacktraceRequest
	(*GetStacktraceResponse)(nil),  // 7: tracee.v1beta1.GetStacktraceResponse
	(EventId)(0),                   // 8: tracee.v1beta1.EventId
}
var file_api_v1beta1_diagnostic_proto_depIdxs = []int32{
	3, // 0: tracee.v1beta1.GetMetricsResponse.BPFEventStats:type_name -> tracee.v1beta1.BPFEventStats
	8, // 1: tracee.v1beta1.BPFEventStats.id:type_name -> tracee.v1beta1.EventId
	0, // 2: tracee.v1beta1.ChangeLogLevelRequest.level:type_name -> tracee.v1beta1.LogLevel
	1, // 3: tracee.v1beta1.DiagnosticService.GetMetrics:input_type -> tracee.v1beta1.GetMetricsRequest
	4, // 4: tracee.v1beta1.DiagnosticService.ChangeLogLevel:input_type -> tracee.v1beta1.ChangeLogLevelRequest
	6, // 5: tracee.v1beta1.DiagnosticService.GetStacktrace:input_type -> tracee.v1beta1.GetStacktraceRequest
	2, // 6: tracee.v1beta1.DiagnosticService.GetMetrics:output_type -> tracee.v1beta1.GetMetricsResponse
	5, // 7: tracee.v1beta1.DiagnosticService.ChangeLogLevel:output_type -> tracee.v1beta1.ChangeLogLevelResponse
	7, // 8: tracee.v1beta1.DiagnosticService.GetStacktrace:output_type -> tracee.v1beta1.GetStacktraceResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1beta1_diagnostic_proto_init() }
func file_api_v1beta1_diagnostic_proto_init() {
	if File_api_v1beta1_diagnostic_proto != nil {
		return
	}
	file_api_v1beta1_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_diagnostic_proto_rawDesc), len(file_api_v1beta1_diagnostic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta1_diagnostic_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_diagnostic_proto_depIdxs,
		EnumInfos:         file_api_v1beta1_diagnostic_proto_enumTypes,
		MessageInfos:      file_api_v1beta1_diagnostic_proto_msgTypes,
	}.Build()
	File_api_v1beta1_diagnostic_proto = out.File
	file_api_v1beta1_diagnostic_proto_goTypes = nil
	file_api_v1beta1_diagnostic_proto_depIdxs = nil
}
