// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/threat.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_LOW      Severity = 1
	Severity_MEDIUM   Severity = 2
	Severity_HIGH     Severity = 3
	Severity_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1beta1_threat_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_api_v1beta1_threat_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_api_v1beta1_threat_proto_rawDescGZIP(), []int{0}
}

type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Mitre         *Mitre                 `protobuf:"bytes,2,opt,name=mitre,proto3" json:"mitre,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=tracee.v1beta1.Severity" json:"severity,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_api_v1beta1_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_threat_proto_rawDescGZIP(), []int{0}
}

func (x *Threat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Threat) GetMitre() *Mitre {
	if x != nil {
		return x.Mitre
	}
	return nil
}

func (x *Threat) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *Threat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Threat) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Mitre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tactic        *MitreTactic           `protobuf:"bytes,1,opt,name=tactic,proto3" json:"tactic,omitempty"`
	Technique     *MitreTechnique        `protobuf:"bytes,2,opt,name=technique,proto3" json:"technique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mitre) Reset() {
	*x = Mitre{}
	mi := &file_api_v1beta1_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mitre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mitre) ProtoMessage() {}

func (x *Mitre) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mitre.ProtoReflect.Descriptor instead.
func (*Mitre) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_threat_proto_rawDescGZIP(), []int{1}
}

func (x *Mitre) GetTactic() *MitreTactic {
	if x != nil {
		return x.Tactic
	}
	return nil
}

func (x *Mitre) GetTechnique() *MitreTechnique {
	if x != nil {
		return x.Technique
	}
	return nil
}

type MitreTactic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitreTactic) Reset() {
	*x = MitreTactic{}
	mi := &file_api_v1beta1_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitreTactic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitreTactic) ProtoMessage() {}

func (x *MitreTactic) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitreTactic.ProtoReflect.Descriptor instead.
func (*MitreTactic) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_threat_proto_rawDescGZIP(), []int{2}
}

func (x *MitreTactic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MitreTechnique struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitreTechnique) Reset() {
	*x = MitreTechnique{}
	mi := &file_api_v1beta1_threat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitreTechnique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitreTechnique) ProtoMessage() {}

func (x *MitreTechnique) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_threat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitreTechnique.ProtoReflect.Descriptor instead.
func (*MitreTechnique) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_threat_proto_rawDescGZIP(), []int{3}
}

func (x *MitreTechnique) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MitreTechnique) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1beta1_threat_proto protoreflect.FileDescriptor

const file_api_v1beta1_threat_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1beta1/threat.proto\x12\x0etracee.v1beta1\"\xa8\x02\n" +
	"\x06Threat\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12+\n" +
	"\x05mitre\x18\x02 \x01(\v2\x15.tracee.v1beta1.MitreR\x05mitre\x124\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x18.tracee.v1beta1.SeverityR\bseverity\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12F\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2&.tracee.v1beta1.Threat.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x05Mitre\x123\n" +
	"\x06tactic\x18\x01 \x01(\v2\x1b.tracee.v1beta1.MitreTacticR\x06tactic\x12<\n" +
	"\ttechnique\x18\x02 \x01(\v2\x1e.tracee.v1beta1.MitreTechniqueR\ttechnique\"!\n" +
	"\vMitreTactic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x0eMitreTechnique\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04B+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_threat_proto_rawDescOnce sync.Once
	file_api_v1beta1_threat_proto_rawDescData []byte
)

func file_api_v1beta1_threat_proto_rawDescGZIP() []byte {
	file_api_v1beta1_threat_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_threat_proto_rawDesc), len(file_api_v1beta1_threat_proto_rawDesc)))
	})
	return file_api_v1beta1_threat_proto_rawDescData
}

var file_api_v1beta1_threat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1beta1_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1beta1_threat_proto_goTypes = []any{
	(Severity)(0),          // 0: tracee.v1beta1.Severity
	(*Threat)(nil),         // 1: tracee.v1beta1.Threat
	(*Mitre)(nil),          // 2: tracee.v1beta1.Mitre
	(*MitreTactic)(nil),    // 3: tracee.v1beta1.MitreTactic
	(*MitreTechnique)(nil), // 4: tracee.v1beta1.MitreTechnique
	nil,                    // 5: tracee.v1beta1.Threat.PropertiesEntry
}
var file_api_v1beta1_threat_proto_depIdxs = []int32{
	2, // 0: tracee.v1beta1.Threat.mitre:type_name -> tracee.v1beta1.Mitre
	0, // 1: tracee.v1beta1.Threat.severity:type_name -> tracee.v1beta1.Severity
	5, // 2: tracee.v1beta1.Threat.properties:type_name -> tracee.v1beta1.Threat.PropertiesEntry
	3, // 3: tracee.v1beta1.Mitre.tactic:type_name -> tracee.v1beta1.MitreTactic
	4, // 4: tracee.v1beta1.Mitre.technique:type_name -> tracee.v1beta1.MitreTechnique
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1beta1_threat_proto_init() }
func file_api_v1beta1_threat_proto_init() {
	if File_api_v1beta1_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_threat_proto_rawDesc), len(file_api_v1beta1_threat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1beta1_threat_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_threat_proto_depIdxs,
		EnumInfos:         file_api_v1beta1_threat_proto_enumTypes,
		MessageInfos:      file_api_v1beta1_threat_proto_msgTypes,
	}.Build()
	File_api_v1beta1_threat_proto = out.File
	file_api_v1beta1_threat_proto_goTypes = nil
	file_api_v1beta1_threat_proto_depIdxs = nil
}
