// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1beta1/tracee.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{0}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetEventDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventNames    []string               `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"` // TODO: tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDefinitionsRequest) Reset() {
	*x = GetEventDefinitionsRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDefinitionsRequest) ProtoMessage() {}

func (x *GetEventDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*GetEventDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventDefinitionsRequest) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

type GetEventDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*EventDefinition     `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDefinitionsResponse) Reset() {
	*x = GetEventDefinitionsResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDefinitionsResponse) ProtoMessage() {}

func (x *GetEventDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*GetEventDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventDefinitionsResponse) GetDefinitions() []*EventDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

type EnableEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableEventRequest) Reset() {
	*x = EnableEventRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableEventRequest) ProtoMessage() {}

func (x *EnableEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableEventRequest.ProtoReflect.Descriptor instead.
func (*EnableEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{4}
}

func (x *EnableEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableEventResponse) Reset() {
	*x = EnableEventResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableEventResponse) ProtoMessage() {}

func (x *EnableEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableEventResponse.ProtoReflect.Descriptor instead.
func (*EnableEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{5}
}

type DisableEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableEventRequest) Reset() {
	*x = DisableEventRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableEventRequest) ProtoMessage() {}

func (x *DisableEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableEventRequest.ProtoReflect.Descriptor instead.
func (*DisableEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{6}
}

func (x *DisableEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableEventResponse) Reset() {
	*x = DisableEventResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableEventResponse) ProtoMessage() {}

func (x *DisableEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableEventResponse.ProtoReflect.Descriptor instead.
func (*DisableEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{7}
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []string               `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEventsRequest) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *StreamEventsRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEventsResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{10}
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyNames   []string               `protobuf:"bytes,1,rep,name=policy_names,json=policyNames,proto3" json:"policy_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{11}
}

func (x *ListPoliciesResponse) GetPolicyNames() []string {
	if x != nil {
		return x.PolicyNames
	}
	return nil
}

type ApplyPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policy is a single policy definition in the YAML/JSON policy-file format. It is added if new, or
	// replaced if a policy with the same name already exists (upsert).
	Policy        string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyRequest) Reset() {
	*x = ApplyPolicyRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyRequest) ProtoMessage() {}

func (x *ApplyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyPolicyRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type ApplyPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyName    string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyResponse) Reset() {
	*x = ApplyPolicyResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyResponse) ProtoMessage() {}

func (x *ApplyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyPolicyResponse) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

type RemovePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyRequest) Reset() {
	*x = RemovePolicyRequest{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyRequest) ProtoMessage() {}

func (x *RemovePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyRequest.ProtoReflect.Descriptor instead.
func (*RemovePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{14}
}

func (x *RemovePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemovePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyResponse) Reset() {
	*x = RemovePolicyResponse{}
	mi := &file_api_v1beta1_tracee_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyResponse) ProtoMessage() {}

func (x *RemovePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_tracee_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyResponse.ProtoReflect.Descriptor instead.
func (*RemovePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_tracee_proto_rawDescGZIP(), []int{15}
}

var File_api_v1beta1_tracee_proto protoreflect.FileDescriptor

const file_api_v1beta1_tracee_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1beta1/tracee.proto\x12\x0etracee.v1beta1\x1a google/protobuf/field_mask.proto\x1a\x17api/v1beta1/event.proto\x1a\x1capi/v1beta1/definition.proto\x1a\"api/v1beta1/detector_catalog.proto\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"=\n" +
	"\x1aGetEventDefinitionsRequest\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\"`\n" +
	"\x1bGetEventDefinitionsResponse\x12A\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x1f.tracee.v1beta1.EventDefinitionR\vdefinitions\"(\n" +
	"\x12EnableEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13EnableEventResponse\")\n" +
	"\x13DisableEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DisableEventResponse\"a\n" +
	"\x13StreamEventsRequest\x12\x1a\n" +
	"\bpolicies\x18\x01 \x03(\tR\bpolicies\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"C\n" +
	"\x14StreamEventsResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.tracee.v1beta1.EventR\x05event\"\x15\n" +
	"\x13ListPoliciesRequest\"9\n" +
	"\x14ListPoliciesResponse\x12!\n" +
	"\fpolicy_names\x18\x01 \x03(\tR\vpolicyNames\",\n" +
	"\x12ApplyPolicyRequest\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\"6\n" +
	"\x13ApplyPolicyResponse\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\")\n" +
	"\x13RemovePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14RemovePolicyResponse2\xe2\x06\n" +
	"\rTraceeService\x12n\n" +
	"\x13GetEventDefinitions\x12*.tracee.v1beta1.GetEventDefinitionsRequest\x1a+.tracee.v1beta1.GetEventDefinitionsResponse\x12n\n" +
	"\x13GetDetectorsCatalog\x12*.tracee.v1beta1.GetDetectorsCatalogRequest\x1a+.tracee.v1beta1.GetDetectorsCatalogResponse\x12[\n" +
	"\fStreamEvents\x12#.tracee.v1beta1.StreamEventsRequest\x1a$.tracee.v1beta1.StreamEventsResponse0\x01\x12V\n" +
	"\vEnableEvent\x12\".tracee.v1beta1.EnableEventRequest\x1a#.tracee.v1beta1.EnableEventResponse\x12Y\n" +
	"\fDisableEvent\x12#.tracee.v1beta1.DisableEventRequest\x1a$.tracee.v1beta1.DisableEventResponse\x12Y\n" +
	"\fListPolicies\x12#.tracee.v1beta1.ListPoliciesRequest\x1a$.tracee.v1beta1.ListPoliciesResponse\x12V\n" +
	"\vApplyPolicy\x12\".tracee.v1beta1.ApplyPolicyRequest\x1a#.tracee.v1beta1.ApplyPolicyResponse\x12Y\n" +
	"\fRemovePolicy\x12#.tracee.v1beta1.RemovePolicyRequest\x1a$.tracee.v1beta1.RemovePolicyResponse\x12S\n" +
	"\n" +
	"GetVersion\x12!.tracee.v1beta1.GetVersionRequest\x1a\".tracee.v1beta1.GetVersionResponseB+Z)github.co/aquasecurity/tracee/api/v1beta1b\x06proto3"

var (
	file_api_v1beta1_tracee_proto_rawDescOnce sync.Once
	file_api_v1beta1_tracee_proto_rawDescData []byte
)

func file_api_v1beta1_tracee_proto_rawDescGZIP() []byte {
	file_api_v1beta1_tracee_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_tracee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1beta1_tracee_proto_rawDesc), len(file_api_v1beta1_tracee_proto_rawDesc)))
	})
	return file_api_v1beta1_tracee_proto_rawDescData
}

var file_api_v1beta1_tracee_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_v1beta1_tracee_proto_goTypes = []any{
	(*GetVersionRequest)(nil),           // 0: tracee.v1beta1.GetVersionRequest
	(*GetVersionResponse)(nil),          // 1: tracee.v1beta1.GetVersionResponse
	(*GetEventDefinitionsRequest)(nil),  // 2: tracee.v1beta1.GetEventDefinitionsRequest
	(*GetEventDefinitionsResponse)(nil), // 3: tracee.v1beta1.GetEventDefinitionsResponse
	(*EnableEventRequest)(nil),          // 4: tracee.v1beta1.EnableEventRequest
	(*EnableEventResponse)(nil),         // 5: tracee.v1beta1.EnableEventResponse
	(*DisableEventRequest)(nil),         // 6: tracee.v1beta1.DisableEventRequest
	(*DisableEventResponse)(nil),        // 7: tracee.v1beta1.DisableEventResponse
	(*StreamEventsRequest)(nil),         // 8: tracee.v1beta1.StreamEventsRequest
	(*StreamEventsResponse)(nil),        // 9: tracee.v1beta1.StreamEventsResponse
	(*ListPoliciesRequest)(nil),         // 10: tracee.v1beta1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),        // 11: tracee.v1beta1.ListPoliciesResponse
	(*ApplyPolicyRequest)(nil),          // 12: tracee.v1beta1.ApplyPolicyRequest
	(*ApplyPolicyResponse)(nil),         // 13: tracee.v1beta1.ApplyPolicyResponse
	(*RemovePolicyRequest)(nil),         // 14: tracee.v1beta1.RemovePolicyRequest
	(*RemovePolicyResponse)(nil),        // 15: tracee.v1beta1.RemovePolicyResponse
	(*EventDefinition)(nil),             // 16: tracee.v1beta1.EventDefinition
	(*fieldmaskpb.FieldMask)(nil),       // 17: google.protobuf.FieldMask
	(*Event)(nil),                       // 18: tracee.v1beta1.Event
	(*GetDetectorsCatalogRequest)(nil),  // 19: tracee.v1beta1.GetDetectorsCatalogRequest
	(*GetDetectorsCatalogResponse)(nil), // 20: tracee.v1beta1.GetDetectorsCatalogResponse
}
var file_api_v1beta1_tracee_proto_depIdxs = []int32{
	16, // 0: tracee.v1beta1.GetEventDefinitionsResponse.definitions:type_name -> tracee.v1beta1.EventDefinition
	17, // 1: tracee.v1beta1.StreamEventsRequest.mask:type_name -> google.protobuf.FieldMask
	18, // 2: tracee.v1beta1.StreamEventsResponse.event:type_name -> tracee.v1beta1.Event
	2,  // 3: tracee.v1beta1.TraceeService.GetEventDefinitions:input_type -> tracee.v1beta1.GetEventDefinitionsRequest
	19, // 4: tracee.v1beta1.TraceeService.GetDetectorsCatalog:input_type -> tracee.v1beta1.GetDetectorsCatalogRequest
	8,  // 5: tracee.v1beta1.TraceeService.StreamEvents:input_type -> tracee.v1beta1.StreamEventsRequest
	4,  // 6: tracee.v1beta1.TraceeService.EnableEvent:input_type -> tracee.v1beta1.EnableEventRequest
	6,  // 7: tracee.v1beta1.TraceeService.DisableEvent:input_type -> tracee.v1beta1.DisableEventRequest
	10, // 8: tracee.v1beta1.TraceeService.ListPolicies:input_type -> tracee.v1beta1.ListPoliciesRequest
	12, // 9: tracee.v1beta1.TraceeService.ApplyPolicy:input_type -> tracee.v1beta1.ApplyPolicyRequest
	14, // 10: tracee.v1beta1.TraceeService.RemovePolicy:input_type -> tracee.v1beta1.RemovePolicyRequest
	0,  // 11: tracee.v1beta1.TraceeService.GetVersion:input_type -> tracee.v1beta1.GetVersionRequest
	3,  // 12: tracee.v1beta1.TraceeService.GetEventDefinitions:output_type -> tracee.v1beta1.GetEventDefinitionsResponse
	20, // 13: tracee.v1beta1.TraceeService.GetDetectorsCatalog:output_type -> tracee.v1beta1.GetDetectorsCatalogResponse
	9,  // 14: tracee.v1beta1.TraceeService.StreamEvents:output_type -> tracee.v1beta1.StreamEventsResponse
	5,  // 15: tracee.v1beta1.TraceeService.EnableEvent:output_type -> tracee.v1beta1.EnableEventResponse
	7,  // 16: tracee.v1beta1.TraceeService.DisableEvent:output_type -> tracee.v1beta1.DisableEventResponse
	11, // 17: tracee.v1beta1.TraceeService.ListPolicies:output_type -> tracee.v1beta1.ListPoliciesResponse
	13, // 18: tracee.v1beta1.TraceeService.ApplyPolicy:output_type -> tracee.v1beta1.ApplyPolicyResponse
	15, // 19: tracee.v1beta1.TraceeService.RemovePolicy:output_type -> tracee.v1beta1.RemovePolicyResponse
	1,  // 20: tracee.v1beta1.TraceeService.GetVersion:output_type -> tracee.v1beta1.GetVersionResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1beta1_tracee_proto_init() }
func file_api_v1beta1_tracee_proto_init() {
	if File_api_v1beta1_tracee_proto != nil {
		return
	}
	file_api_v1beta1_event_proto_init()
	file_api_v1beta1_definition_proto_init()
	file_api_v1beta1_detector_catalog_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1beta1_tracee_proto_rawDesc), len(file_api_v1beta1_tracee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta1_tracee_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_tracee_proto_depIdxs,
		MessageInfos:      file_api_v1beta1_tracee_proto_msgTypes,
	}.Build()
	File_api_v1beta1_tracee_proto = out.File
	file_api_v1beta1_tracee_proto_goTypes = nil
	file_api_v1beta1_tracee_proto_depIdxs = nil
}
