---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:0.12.0
        imagePullPolicy: IfNotPresent
        args:
          - --filter set=signatures
          - --output json
          - --containers
        env:
        - name: LIBBPFGO_OSRELEASE_FILE
          value: /etc/os-release-host
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-tracee
          mountPath: /tmp/tracee
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        - name: docker
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: containerd
          mountPath: /var/run/containerd/containerd.sock
          readOnly: true
        - name: crio
          mountPath: /var/run/crio/crio.sock
          readOnly: true
        - name: podman
          mountPath: /var/run/podman/podman.sock
          readOnly: true
        # NOTE: Resource consumption will vary between different use cases and
        # workload characteristics. User should monitor tracee for resource
        # consumption before enabling resource limits. Capping tracee
        # resources may cause loss of events and miss detections. Golang
        # signatures outperforms REGO signatures, use less HW resources,
        # and are preferred if that is an option.
        # resources:
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 1Gi # tracee has a 512MB in-memory events cache enabled by default
        #   requests:
        #     cpu: "1"
        #     memory: 1Gi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - name: tmp-tracee
        hostPath:
          path: /tmp/tracee
      - name: etc-os-release 
        hostPath:
          path: /etc/os-release
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: containerd
        hostPath:
          path: /var/run/containerd/containerd.sock
      - name: crio
        hostPath:
          path: /var/run/crio/crio.sock
      - name: podman
        hostPath:
          path: /var/run/podman/podman.sock
