#!/usr/bin/env bash

mock_tracee_ebpf() {
  echo 'event1'
}

mock_falco_sidekick() {
  echo $cmd $@
}


mock_tracee_rules() {
  if [ $1 = '--input-tracee=file:stdin' ]; then
    read -r line
    echo "processed: $line"
  fi
}

cmd=$(basename $0)
[ "$MOCK_LOG" ] && echo "$cmd $@" >> "$MOCK_LOG"
case "$cmd" in 
  'tracee-ebpf')
    mock_tracee_ebpf $@
    ;;
  'tracee-rules')
    mock_tracee_rules $@
    ;;
  'falco-sidekick')
    mock_falco_sidekick $@
    ;;
  *)
    ;;
esac
