FROM ubuntu:26.04@sha256:53958ec7b67c2c9355df922dd08dbf0360611f8c3cdb656875e81873db9ffdba

ARG DEBIAN_FRONTEND="noninteractive"
ENV DEBCONF_NOWARNINGS="yes"

RUN apt-get update -y && \
    apt-get install -y make wget

ARG PANDOC_VERSION="3.2"
ARG PANDOC_DEB="pandoc-${PANDOC_VERSION}-1-amd64.deb"

RUN wget -q https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${PANDOC_DEB} && \
    dpkg -i ${PANDOC_DEB}

WORKDIR /tracee
