FROM ubuntu:24.04@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c

ARG DEBIAN_FRONTEND="noninteractive"
ENV DEBCONF_NOWARNINGS="yes"

RUN apt-get update -y && \
    apt-get install -y make wget

ARG PANDOC_VERSION="3.2"
ARG PANDOC_DEB="pandoc-${PANDOC_VERSION}-1-amd64.deb"

RUN wget -q https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${PANDOC_DEB} && \
    dpkg -i ${PANDOC_DEB}

WORKDIR /tracee
