FROM ubuntu:24.04@sha256:353675e2a41babd526e2b837d7ec780c2a05bca0164f7ea5dbbd433d21d166fc

ARG DEBIAN_FRONTEND="noninteractive"
ENV DEBCONF_NOWARNINGS="yes"

RUN apt-get update -y && \
    apt-get install -y make wget

ARG PANDOC_VERSION="3.2"
ARG PANDOC_DEB="pandoc-${PANDOC_VERSION}-1-amd64.deb"

RUN wget -q https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${PANDOC_DEB} && \
    dpkg -i ${PANDOC_DEB}

WORKDIR /tracee
