#
# DEPRECATED: the checkers moved into the main Makefile (mk/checks.mk) and
# run in the containerized build environment by default. This shim forwards
# the old target names and will be removed in a future release.
#
#   make -f builder/Makefile.checkers fmt-check   ->  make check-fmt
#   make -f builder/Makefile.checkers fmt-fix     ->  make fix-fmt
#   make -f builder/Makefile.checkers lint-check  ->  make check-lint
#   make -f builder/Makefile.checkers code-check  ->  make check-code
#

MAKEFLAGS += --no-print-directory

.PHONY: all help
all help:
	@echo "DEPRECATED: use 'make check-fmt|fix-fmt|check-lint|check-code' instead"

.PHONY: fmt-check fmt-fix lint-check code-check
fmt-check:
	@echo "DEPRECATED: use 'make check-fmt' instead" >&2
	@make check-fmt
fmt-fix:
	@echo "DEPRECATED: use 'make fix-fmt' instead" >&2
	@make fix-fmt
lint-check:
	@echo "DEPRECATED: use 'make check-lint' instead" >&2
	@make check-lint
code-check:
	@echo "DEPRECATED: use 'make check-code' instead" >&2
	@make check-code
