global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9100"]

  - job_name: "tracee"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:3366"]
