kind: ConfigMap
apiVersion: v1
metadata:
  name: tracee-webhook-config
data:
  cfg.yaml: |-
    debug: true
    # Reference: https://github.com/falcosecurity/falcosidekick/blob/master/config_example.yaml
    # slack:
    #   webhookurl: "https://hooks.slack.com/xxxxxxxx"
    # teams:
    #   webhookurl: "https://xxxxxxx"