apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
  name: new-pids
  annotations:
    description: traces openat and security_file_open for new pids
spec:
  scope: 
    - pid=new
  rules:
    - event: openat
    - event: security_file_open
