apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
  name: comm-strace
  annotations:
    description: traces sched_process_exec and sched_process_exit for the command strace
spec:
  scope: 
    - comm=strace
  rules:
    - event: sched_process_exec
    - event: sched_process_exit

