#
# When a PR is opened or updated: Label it based on files being changed
#
name: "Labeler"
on:
  - pull_request_target
jobs:
  triage:
    name: Triage Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: false
          configuration-path: .github/labeler.yml
