name: libbpfgo-selfhosted
on: 
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [centos-8.2-linux-4.18]
    defaults:
      run:
        working-directory: libbpfgo
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: selftest
        run: |
          sudo ./selftest/run.sh
