name: pr-rules
on: 
  pull_request:
    paths: 
      - "tracee-rules/**"
jobs:
  build-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: tracee-rules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi
      - name: Build 
        run: make build
      - name: Build signatures
        run: make rules
      - name: Test
        run: make test
