name: pr-rules
on: 
  pull_request:
    paths: 
      - "tracee-rules/**"
jobs:
  build-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: tracee-rules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build tracee-builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.builder
          load: true
          tags: tracee-builder:latest
      - name: Build 
        run: make build
      - name: Build signatures
        run: make rules
      - name: Run Tests
        run: make test DOCKER=1