name: pr-rules
on: 
  pull_request:
    paths: 
      - "tracee-rules/**"
jobs:
  build-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: tracee-rules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          make build
      - name: Build signatures
        run: make rules
      - name: Run Tests
        run: DOCKER_BUILDKIT=1 make test DOCKER=1