name: pr-sanity
on:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-20.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Tracee sanity tests
        run: |
          make sanity
