name: pr-sanity
on:
  pull_request:

jobs:
  sanity-test:
    name: "Sanity Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [centos-8.2-linux-4.18]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: Run Tracee sanity tests
      run: |
        make sanity
