#
# TODO: remove this
#
name: Release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The tag to be released, e.g. v0.0.1
        required: true
jobs:
  release-temporary:
    name: Release Temporary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          submodules: true
          fetch-depth: 0
      - name: Login to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to docker.io registry
        run: |
          TAG=$(echo ${{ github.event.inputs.ref }} | sed -e "s/v//gI")
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker manifest create aquasec/tracee:latest \
            aquasec/tracee:x86_64-${TAG} \
            aquasec/tracee:aarch64-${TAG}
          docker manifest create aquasec/tracee:${TAG} \
            aquasec/tracee:x86_64-${TAG} \
            aquasec/tracee:aarch64-${TAG}
          docker manifest push aquasec/tracee:latest
          docker manifest push aquasec/tracee:${TAG}
        shell: bash
