#
# When tag vXXX is pushed: Release Tracee
#
name: Release ARM64 only
on:
  workflow_dispatch: {}
jobs:
  release-arm64:
    name: Release ARM64
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on:
      [
        "github-self-hosted_ami-03217ce7c37572c4d_${{ github.event.number }}-${{ github.run_id }}",
      ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: AWS Environment
        run: |
          dmidecode
      - name: Login to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          make -f builder/Makefile.release
        # NO tracee:latest (historical reason: amd64 only)
        # use :aarch64 as tag for the latest image
        # use :aarch64-v0.xx.0 for versioned image
      - name: Publish to docker.io registry
        run: |
          TAG=$(git describe --tags --abbrev=0 | sed -e "s/v//gI")
          ARCH=$(uname -m)
          docker image tag tracee:latest aquasec/tracee:${ARCH}
          docker image tag tracee:latest aquasec/tracee:${ARCH}-${TAG}
          docker image push aquasec/tracee:${ARCH}
          docker image push aquasec/tracee:${ARCH}-${TAG}
