#
# Daily Test: Test generating OS packages
#
name: OS Packages (DAILY)
on:
  workflow_dispatch: {}
  schedule:
    # Daily At 04:00
    - cron: '0 4 * * 0'
jobs:
  packaging:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [
          # llvm repository is broken for bionic
          # {distro: ubuntu, version: bionic},
          {distro: ubuntu, version: focal},
          {distro: ubuntu, version: jammy},
          {distro: ubuntu, version: kinetic},
          {distro: fedora, version: 36},
          {distro: fedora, version: 37},
          ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch Tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
      - name: "Build Package"
        run: |
          export GIT_TAG=${{steps.tagger.outputs.tag}}
          script --return -c "make -f builder/Makefile.packaging ${{ matrix.flavor.distro }}-bin-${{ matrix.flavor.version }}"
          find ./dist | grep -Eq "(deb|rpm)" && found=1
          if [[ $found -ne 1 ]]; then
            echo "Could not generate OS package, check errors"
            exit 1
          fi
