---
# Test signatures on CRON schedule or on demand.
name: Test Signatures

on:
  workflow_dispatch: { }
  schedule:
    - cron: "0 0 * * *"

env:
  GO_VERSION: "1.17"
  OPA_VERSION: "v0.35.0"

jobs:
  e2e-test-signatures:
    name: "[E2E] Test Signatures"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: ${{ env.GO_VERSION }}
          opa-version: ${{ env.OPA_VERSION }}
      - name: Build tracee image (slim w/ BTFHUB)
        run: |
          BTFHUB=1 make -f builder/Makefile.tracee-container build-tracee
      - name: Install BPF
        run: |
          make install-bpf-nocore
      - name: Run tests
        run: |
          docker image pull aquasec/tracee-tester:latest
          go test -v -run "TestTraceeSignatures" ./tests/e2e/e2e_test.go \
            -tracee-image-ref "tracee:latest" \
            -tracee-tester-image-ref "aquasec/tracee-tester:latest"
