#
# Daily Test: TRC-2 with selected kernels.
#
name: CO-RE (DAILY)
on:
  workflow_dispatch: {}
  schedule:
    # At 00:00 every day
    - cron: '0 0 * * *'
jobs:
  CO-RE:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        signature:
          - "TRC-2"
        distro:
          - "stream8"
          - "stream9"
          - "fedora34"
          - "fedora35"
          - "fedora36"
          - "focal"
          - "focalhwe"
          - "jammy"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Pull test container image"
        run: |
          docker image pull rafaeldtinoco/tracee-distro-tester:${{ matrix.distro }}
      - name: "Run tests"
        run: |
          docker run --rm --privileged -v $(pwd):/tracee:rw \
            -e kvm_accel="tcg" \
            -e test_name=${{ matrix.signature }} \
            -e non_core=0 \
            -t rafaeldtinoco/tracee-distro-tester:${{ matrix.distro }}
