#
# Daily CO-RE tests with all the signatures.
#
name: CO-RE (DAILY)
on:
  workflow_dispatch: {}
  schedule:
    # At 04:00 every day
    - cron: '0 4 * * *'
jobs:
  CO-RE:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        signature:
          - "TRC-2"
          - "TRC-3"
          - "TRC-4"
          - "TRC-5"
          - "TRC-7"
          #- "TRC-8" (issue: #1483)
          - "TRC-9"
          - "TRC-10"
          - "TRC-11"
          - "TRC-12"
          - "TRC-14"
        distro:
          - "stream8-4.18"
          - "stream9-5.14"
          - "fedora34-5.11"
          - "fedora35-5.14"
          - "fedora36-5.17"
          - "focal-5.4"
          - "focalhwe-5.13"
          - "jammy-5.15"
          - "gkekernel1.21.11-5.4"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      #- name: "Pull test container image"
      #  run: |
      #    distro=$(echo ${{ matrix.distro }} | cut -d'-' -f1)
      #    docker image pull rafaeldtinoco/tracee-distro-tester:$distro
      - name: "Run tests"
        run: |
          distro=$(echo ${{ matrix.distro }} | cut -d'-' -f1)
          docker run --rm --privileged -v $(pwd):/tracee:rw \
            -e kvm_accel="kvm" \
            -e test_name=${{ matrix.signature }} \
            -e non_core=0 \
            -e cpus=4 -e mem=4 \
            -t rafaeldtinoco/tracee-distro-tester:$distro
