#
# Daily Test: TRC-2 with selected kernels.
#
name: CO-RE (DAILY)
on:
  workflow_dispatch: {}
  schedule:
    # At 00:00 every day
    - cron: '0 0 * * *'
jobs:
  CO-RE:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        signature:
          - "TRC-2"
        kernel:
          - "4.19.238-stable"
          - "5.4.166-ubuntu+"
          - "5.4.188-amzn2"
          - "5.4.189-stable"
          - "5.8.18-ubuntu"
          - "5.10.111-stable"
          - "5.11.22-ubuntu"
          - "5.11.22-fedora32"
          - "5.13.19-ubuntu"
          - "5.14.18-fedora33"
          - "5.15.30-ubuntu"
          - "5.15.34-stable"
          - "5.16.18-stable"
          - "5.16.19-fedora34"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Pull test container image"
        run: |
          docker image pull rafaeldtinoco/tracee-test-kernels:latest
      - name: "Run tests"
        run: |
          docker run --rm --privileged -v $(pwd):/tracee:rw \
            -e kvm_accel="tcg" \
            -e kern_version=${{ matrix.kernel }} \
            -e test_name=${{ matrix.signature }} \
            -e is_noncore=0 \
            -t rafaeldtinoco/tracee-test-kernels:latest
