#
# Weekly Test: TRC-2 with selected kernels.
#
name: NON CO-RE (WEEKLY)
on:
  workflow_dispatch: {}
  schedule:
    # At 06:00 on Saturdays
    - cron: '0 6 * * 6'
jobs:
  NON-CO-RE:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        signature:
          - "TRC-2"
          - "TRC-3"
          - "TRC-4"
          - "TRC-5"
          - "TRC-7"
          - "TRC-8"
          - "TRC-9"
          - "TRC-10"
          - "TRC-11"
          - "TRC-12"
          - "TRC-14"
        distro:
          - "stream8-4.18"
          - "stream9-5.14"
          - "fedora34-5.11"
          - "fedora35-5.14"
          - "fedora36-5.17"
          - "focal-5.4"
          - "focalhwe-5.13"
          - "jammy-5.15"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Pull test container image"
        run: |
          distro=$(echo ${{ matrix.distro }} | cut -d'-' -f1)
          docker image pull rafaeldtinoco/tracee-distro-tester:$distro
      - name: "Run tests"
        run: |
          distro=$(echo ${{ matrix.distro }} | cut -d'-' -f1)
          docker run --rm --privileged -v $(pwd):/tracee:rw \
            -e kvm_accel="tcg" \
            -e test_name=${{ matrix.signature }} \
            -e non_core=1 \
            -t rafaeldtinoco/tracee-distro-tester:$distro
