name: Echo AWS_REGION to File

on:
  workflow_dispatch:

jobs:
  write-aws-region:
    runs-on: aquasec-com-arc-runner-set-amd64

    steps:
      - name: Echo AWS_REGION to file
        run: echo "${{ secrets.AWS_REGION }}" > /tmp/AWS_REGION.txt

      - name: Echo AWS_REGION to file
        run: sleep 60