{
 "title": "TRACEE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Filtered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_filtered[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_filtered  {job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered/Total ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_events_total", "legendFormat": "__auto" },
    { "expr": "tracee_ebpf_events_filtered", "legendFormat": "__auto" },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Lost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_lostevents_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_lostevents_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost/Total ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_events_total", "legendFormat": "__auto" },
    { "expr": "tracee_ebpf_lostevents_total", "legendFormat": "__auto" },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  { "title": "Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Malloc Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Malloc Rate (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Malloc Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free/Malloc ratio",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"tracee\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_frees_total{job=\"tracee\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Free Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Rate (avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job=\"tracee\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_frees_total{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"tracee\"}",
     "legendFormat": "in use"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"tracee\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"tracee\"}",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "Heap In Use (avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects (avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "GC Pressure Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pressure Data (avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=\"tracee\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pressure Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"tracee\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pressure Time (avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"tracee\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "USER PER CPU TIME STACKED",
     "type": "timeseries",
     "description": "Each line represents ONE SPECIFIC CPU percentage, and all of them are summing ALL USER CPU TIME in a stack.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])*100",
       "legendFormat": "USER"
      }
     ]
    },
    {
     "title": "SYSTEM PERCPU TIME STACKED",
     "type": "timeseries",
     "description": "Each line represents ONE SPECIFIC CPU percentage, and all of them are summing ALL SYSTEM CPU TIME in a stack.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])*100",
       "legendFormat": "SYSTEM"
      }
     ]
    },
    {
     "title": "HOST MEMORY IN GB",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes/1024/1024/1024",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "node_memory_MemFree_bytes/1024/1024/1024",
       "legendFormat": "FREE"
      },
      {
       "expr": "(node_memory_SReclaimable_bytes+node_memory_KReclaimable_bytes)/1024/1024/1024",
       "legendFormat": "RECLAIMABLE"
      },
      {
       "expr": "node_memory_Active_bytes/1024/1024/1024",
       "legendFormat": "ACTIVE"
      },
      {
       "expr": "node_memory_Inactive_bytes/1024/1024/1024",
       "legendFormat": "INACTIVE"
      },
      {
       "expr": "(node_memory_Cached_bytes+node_memory_Buffers_bytes)/1024/1024/1024",
       "legendFormat": "FS CACHE + BUFFERS"
      }
     ]
    },
    {
     "type": "pyroscope-panel",
     "gridPos": { "h": 27, "w": 24, "x": 0, "y": 20 },
     "targets": [
      { "from": "now-1h", "name": "tracee.cpu", "until": "now" }
     ]
    }
   ]
  }
 ]
}